// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXpFq-74AON9r3ti6-_twd4pB3sgwbI7s',
    appId: '1:1074238596827:web:e980c4f0192ef990a84efe',
    messagingSenderId: '1074238596827',
    projectId: 'rice-panicle-analysis',
    authDomain: 'rice-panicle-analysis.firebaseapp.com',
    storageBucket: 'rice-panicle-analysis.firebasestorage.app',
    measurementId: 'G-ESJSE1VN4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALq10hQXaJXoAIU85TFrI3Hz0ThDHj2fc',
    appId: '1:1074238596827:android:dfb8d0419391ac2aa84efe',
    messagingSenderId: '1074238596827',
    projectId: 'rice-panicle-analysis',
    storageBucket: 'rice-panicle-analysis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfZJdrTy8yHa6qbiBeBze_kSh2-7-AiBM',
    appId: '1:1074238596827:ios:97910a31bae0ca52a84efe',
    messagingSenderId: '1074238596827',
    projectId: 'rice-panicle-analysis',
    storageBucket: 'rice-panicle-analysis.firebasestorage.app',
    iosBundleId: 'com.example.ricePanicleAnalysisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfZJdrTy8yHa6qbiBeBze_kSh2-7-AiBM',
    appId: '1:1074238596827:ios:97910a31bae0ca52a84efe',
    messagingSenderId: '1074238596827',
    projectId: 'rice-panicle-analysis',
    storageBucket: 'rice-panicle-analysis.firebasestorage.app',
    iosBundleId: 'com.example.ricePanicleAnalysisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXpFq-74AON9r3ti6-_twd4pB3sgwbI7s',
    appId: '1:1074238596827:web:2eeb4a411125cda7a84efe',
    messagingSenderId: '1074238596827',
    projectId: 'rice-panicle-analysis',
    authDomain: 'rice-panicle-analysis.firebaseapp.com',
    storageBucket: 'rice-panicle-analysis.firebasestorage.app',
    measurementId: 'G-QL2YFSN3PC',
  );
}
